# Generated by Django 4.0.4 on 2022-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitute', models.CharField(max_length=50, verbose_name='Место учебы')),
                ('position', models.CharField(max_length=50, verbose_name='Специальность')),
                ('data_start', models.DateTimeField()),
                ('data_finish', models.DateTimeField()),
                ('progress', models.TextField()),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ['data_start'],
            },
        ),
        migrations.CreateModel(
            name='Hard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills', models.CharField(max_length=50, verbose_name='Софтскилл')),
            ],
            options={
                'verbose_name': 'ХардСкилл',
                'verbose_name_plural': 'ХардСкиллы',
            },
        ),
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_skills', models.CharField(max_length=50, verbose_name='Софтскилл')),
            ],
            options={
                'verbose_name': 'СофтСкилл',
                'verbose_name_plural': 'СофтСкиллы',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место работы')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('data_start', models.DateTimeField()),
                ('data_finish', models.DateTimeField()),
                ('tasks', models.TextField()),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['data_start'],
            },
        ),
    ]
